## Manually rotating the coordinate system of our data


In [1]:
import scipy as sp
import numpy as np
from scipy.stats import ortho_group

Generate a new coordinate system, i.e. a set of N orthonormal vectors (orthogonal vectors of magnitude 1).

Here N = 7, random_state is set to guarantee same results on all runs.

In [2]:
m = ortho_group.rvs(dim=7, random_state=17)
print(m.shape)
print(m.round(decimals=4))

(7, 7)
[[ 0.1621 -0.646  -0.1443  0.2816  0.2061  0.5549  0.3253]
 [-0.2124  0.0144 -0.2472  0.8678 -0.1595 -0.3348 -0.0542]
 [ 0.3167 -0.5881  0.334  -0.0916 -0.3028 -0.5793  0.0816]
 [ 0.6051  0.2927 -0.1234  0.1116  0.5764 -0.3142  0.2992]
 [-0.4431  0.0445  0.7259  0.1691  0.3723 -0.0445  0.3248]
 [ 0.5102  0.3028  0.4895  0.3287 -0.374   0.379  -0.1299]
 [ 0.0744 -0.2392  0.1573  0.1009  0.4791 -0.0077 -0.8202]]


In [6]:
X = np.loadtxt('sqisland.csv',delimiter=',',skiprows=1, usecols=range(2,9))
print("Shape of X: ", X.shape)
print("First 5 observations/datapoints/rows of X: \n", X[:5,:].round(decimals=4))


Shape of X:  (100, 7)
First 5 observations/datapoints/rows of X: 
 [[1.     0.     0.2    0.8    0.522  0.1594 0.3185]
 [0.7937 0.2063 0.196  0.804  0.3927 0.2616 0.3457]
 [0.8064 0.1936 0.198  0.802  0.379  0.2765 0.3445]
 [0.8133 0.1867 0.2    0.8    0.5184 0.1489 0.3327]
 [0.7575 0.2425 0.182  0.818  0.2444 0.287  0.4686]]


Now let's 'rotate' the data, i.e.  project all data points onto the new coordinate system. It's done by simply multiplying the data matrix X by the matrix **m** where each column vector represents the orientation of one of the new axes.

In [7]:
newX = np.matmul(X,m)
print(newX.shape)
print(newX[:5,:].round(decimals=4))

(100, 7)
[[ 0.5832 -0.5342  0.3309  0.5253  0.8941  0.2224  0.4686]
 [ 0.6185 -0.3758  0.2682  0.6615  0.7488  0.0842  0.3136]
 [ 0.6363 -0.3817  0.2676  0.6561  0.7404  0.1012  0.3126]
 [ 0.5106 -0.4177  0.3061  0.6321  0.8352  0.0524  0.3863]
 [ 0.6968 -0.3679  0.1822  0.6812  0.7421  0.071   0.1507]]


In [8]:
# Save the result (which does not include the first 2 columns of sqisland.csv containing the location coordinates).
np.savetxt("newDataMatrix.csv", newX, delimiter=",")

Check what happens when you rotate newX back (by multiplying by the inverse of **m**).

In [9]:
m_inv = np.linalg.inv(m)
there_and_back_X = np.matmul(newX,m_inv)
print(there_and_back_X.shape)
print(there_and_back_X[:5,:].round(decimals=4))

(100, 7)
[[1.     0.     0.2    0.8    0.522  0.1594 0.3185]
 [0.7937 0.2063 0.196  0.804  0.3927 0.2616 0.3457]
 [0.8064 0.1936 0.198  0.802  0.379  0.2765 0.3445]
 [0.8133 0.1867 0.2    0.8    0.5184 0.1489 0.3327]
 [0.7575 0.2425 0.182  0.818  0.2444 0.287  0.4686]]


The 'there-and-back' matrix is equivalent to the original matrix X (bar some rounding errors).